### ISSUE TITLE
Принимается!

### ISSUE THREAD

**Issue by phoenixweiss** [n0maCi/homework_1#1]
Многие моменты приятно удивили:

Тернарники:
https://github.com/n0maCi/homework_1/blob/c2e1874dfb9ae32ac8440199878c00c073376533/script.js#L5-L7

Функции:
https://github.com/n0maCi/homework_1/blob/c2e1874dfb9ae32ac8440199878c00c073376533/script.js#L4

Обработчики событий:
https://github.com/n0maCi/homework_1/blob/c2e1874dfb9ae32ac8440199878c00c073376533/script.js#L17

Контекстная переменная `this`:
https://github.com/n0maCi/homework_1/blob/c2e1874dfb9ae32ac8440199878c00c073376533/script.js#L25

Понятные if / else if / else:
https://github.com/n0maCi/homework_1/blob/c2e1874dfb9ae32ac8440199878c00c073376533/script.js#L8-L14

Всё принимается!

Единственное, когда комментариев много и они длинные, обычно используют написание комментария перед строкой с кодом, в не в той же строке, ибо ширина кода заставляет скроллить, что обычно не есть хорошо.
Ну и со страницы не понятно в каком виде вводить данные, тут просто было бы удобнее видеть какую-то подсказку что в поле нужно ввести 4 параметра через запятую. А также можно ввести пустое поле и по сути это будет интерпретировано как введенный счет. НО это всё мелочи просто на которые обратил внимание.

**Comment by n0maCi** [comment]
Решено.
